// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXfNN0uS6jRsIsMHvjmfJi59z9L_jEDX0',
    appId: '1:1099100588290:web:9eccfe54ec024f043c9a1b',
    messagingSenderId: '1099100588290',
    projectId: 'teamup-a338d',
    authDomain: 'teamup-a338d.firebaseapp.com',
    storageBucket: 'teamup-a338d.firebasestorage.app',
    measurementId: 'G-L636W9P5VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPEh71GgntTEgGhB9QmQlp7O9FZzx-LTQ',
    appId: '1:1099100588290:android:8bd635f463ec9dbc3c9a1b',
    messagingSenderId: '1099100588290',
    projectId: 'teamup-a338d',
    storageBucket: 'teamup-a338d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTbLlIwxD6LCWoKejMDctQ8eMYwbtjDC8',
    appId: '1:1099100588290:ios:6a52b6c7dbe5d15a3c9a1b',
    messagingSenderId: '1099100588290',
    projectId: 'teamup-a338d',
    storageBucket: 'teamup-a338d.firebasestorage.app',
    iosBundleId: 'com.example.teamup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXfNN0uS6jRsIsMHvjmfJi59z9L_jEDX0',
    appId: '1:1099100588290:web:4ff73559b910a7223c9a1b',
    messagingSenderId: '1099100588290',
    projectId: 'teamup-a338d',
    authDomain: 'teamup-a338d.firebaseapp.com',
    storageBucket: 'teamup-a338d.firebasestorage.app',
    measurementId: 'G-MNRJETCX1T',
  );

}